### ISSUE TITLE
Annoyance: Overwrites the informative field in the bottom left with a broken timer

### ISSUE THREAD

**Issue by Moire9** [wakatime/sublime-wakatime#101]
In the bottom right of the screen, Sublime Text often displays useful information depending on the situation, for example, line number and column, or when in the Find dialog, the number of matches and the current match number you're on, etc. However, when WakaTime is installed, this is all overwritten with a completely broken timer or something. It just says "Today: 0 secs" and does nothing. I never realized how much I used this little informative thing until I don't have it now. Here is an image of the bugged timer:
![image](https://user-images.githubusercontent.com/31591796/81099608-0bbca980-8ec0-11ea-8d54-a38f0555f669.png) 

For reference, what it used to look like:
![image](https://user-images.githubusercontent.com/31591796/81099678-255df100-8ec0-11ea-8c87-c485ad7bc131.png) 

Or, when in the search dialog: 
![image](https://user-images.githubusercontent.com/31591796/81099719-3444a380-8ec0-11ea-9f41-873596015b82.png) 

It also displays important Regex errors when you're searching with that:
![image](https://user-images.githubusercontent.com/31591796/81099773-49213700-8ec0-11ea-951e-e3944b795147.png) 

All in all, this is a very useful field that has been replaced with something that does nothing. Please allow us to toggle whether or not that is shown, or, if the Time: 0 secs issue is not planned to be fixed, remove it, as it is not very useful.

**Comment by OpenWaygate** [comment]
Maybe related to https://github.com/wakatime/sublime-wakatime/issues/97

**Comment by zixing8284** [comment]
i solved it by editing the WakaTime.py file Line 338 :
` output = u(output)`
TO
` output = u(output).strip()`
`output` contains `\r\n` characters at the end like `3 hrs 28 mins\r\n` and it seems Sublime Text won't show multiline in the status bar.
now it looks fine:
![cap](https://user-images.githubusercontent.com/6228479/116776784-05deb180-aa9d-11eb-9c80-c0b5dfda7810.PNG)

**Comment by alanhamlett** [comment]
Fixed with 7db5fe0a5d9e942f49931486f60b0d5541289bd8.
