### ISSUE TITLE
cannot download v10.0.0 (2020-02-29)

### ISSUE THREAD

**Issue by williamli** [wakatime/sublime-wakatime#104]

**Comment by alanhamlett** [comment]
Where is this error message displayed?

**Comment by williamli** [comment]
@alanhamlett it just show v9.1.2 as latest release (and I already have it installed).

FYI v10.0.0 is not listed at https://github.com/wakatime/sublime-wakatime/releases

**Comment by alanhamlett** [comment]
Releasing v10.0.0 today.
