### ISSUE TITLE
Checks for latest version on the main thread

### ISSUE THREAD

**Issue by rchl** [wakatime/sublime-wakatime#115]
This package makes a network request on the main thread:

https://github.com/wakatime/sublime-wakatime/blob/28063e3ac465784e9f6ccdb4a55b153405ba66ae/WakaTime.py#L754

That means that if there are issues with the network connection on starting ST, this call will freeze ST for good amount of seconds.

This check should be done on a separate thread.

Potentially the `isCliLatest` check could also be done from a separate thread as it's doing file IO but I don't see this causing issue unless there is something wrong with the hard drive or something.

**Comment by alanhamlett** [comment]
Fixed with c1f58fd05d16ce0746d544f7361d5c537e92b8e8 and released in v11.0.7.

**Comment by rchl** [comment]
Thanks.
