### ISSUE TITLE
Only on Windows, cmd windows open on tab change & saves

### ISSUE THREAD

**Issue by patschi** [wakatime/sublime-wakatime#12]
Hello,

it's very very disturbing that on every tab change or save of any file are popping up like five python cmd windows! Sometimes when I'm programming something the windows pops up and disturbs me while I'm coding. I even sent about 2 days a tweet on your account - no response. 

I installed the latest python version from the page you linked on the sublime-help page and put it with the name "Python" in the Sublime folder and in C:\Progs\ and added the python.exe to my $PATH variable.

I've Windows Ultimate x64. Please fix it. I really love the project, but the much disturbing blinking windows makes me really crazy.

Thanks.

**Comment by StephenKoller** [comment]
I'm seeing this same problem now on Windows 10 (x64) and with Sublime WakaTime 7.0.2

Is this the right place to address this or should I open a new issue?

**Comment by alanhamlett** [comment]
A new issue would be better, with a ton of info to help us find the cause :)
