### ISSUE TITLE
The ability to delete a project?

### ISSUE THREAD

**Issue by tuurbo** [wakatime/sublime-wakatime#16]
title ^

**Comment by daveyjones** [comment]
Can the rule then be deleted, or does it need to persist forever?

**Comment by hrkusa89** [comment]
How?

**Comment by alanhamlett** [comment]
@hrkusa89 https://wakatime.com/help/getting-started/faq#delete-project

**Comment by hrkusa89** [comment]
@alanhamlett Annoying Unknown Project! Not a major pain, though. Love the app nevertheless. Keep on the good work.
