### ISSUE TITLE
Complete list of settings

### ISSUE THREAD

**Issue by Xaelias** [wakatime/sublime-wakatime#24]
Would it be possible to have the complete list of options that we can set in the the config file?
Thx

PS: It would be great if they were just displayed in the default setting file, with their default (and every other possible) values.

PPS: Would it be possible to add the possibility to reset/wipe all data?

**Comment by alanhamlett** [comment]
Added complete list of settings to this doc:
https://github.com/wakatime/wakatime#configuring
