### ISSUE TITLE
Error when saving a file

### ISSUE THREAD

**Issue by dcr30** [wakatime/sublime-wakatime#30]
Sometimes (not always) when I press CTRL+S, I get this error:

![image](https://cloud.githubusercontent.com/assets/3995234/5836410/601b82f8-a186-11e4-95cf-a16453526087.png)

The error says: "Access denied". But before I installed WakaTime I had no such error. Removing WakaTime fixes it.
This error allso appears when I press CTRL+S twice very fast.

And another thing: 
Every time I press CTRL+S and move my cursor on tabs panel, I see the *waiting* cursor:
![image](https://cloud.githubusercontent.com/assets/3995234/5836481/7c911208-a187-11e4-9159-eb2dedff743b.png)
I find it a bit annoying.

**I use Sublime Text 3 in Windows 8.1.**

**Comment by alanhamlett** [comment]
Is this still happening with the latest version of the plugin?

**Comment by alanhamlett** [comment]
Closing this. I'll reopen the issue if it's still a problem.
