### ISSUE TITLE
Remove 'heartbeat' message from Sublime status bar

### ISSUE THREAD

**Issue by kgizdov** [wakatime/sublime-wakatime#32]
Hi,

I (and I guess others) use Sublimelinter and many more linter plugins. Most of these plugins put their active notifications/messages/etc in Sublime's status bar. Since the latest update however, WakaTime plugin also started to put its very long static 'heartbeat' message in there. So now, I have too much text in the status bat for it to be any useful.

I feel like this message is not necessary (vital) to the operation of WakaTime and it doesn't need to be there. Regardless, I think at least it should be an option to display it in the status bar if you really want to or otherwise to disable it. In my opinion, having it appear in the console log is just enough, as it is not showing all the time and does not contribute to clutter.

I also think that the status bar should be kept for real time status updates that require attention/action or otherwise crucial to the current situation. The 'heartbeat' message appears as soon as the WakaTime loads and stays static forever - just taking up precious space. I hope you can address this at your earliest convenience.

Thank you in advance,

**Comment by alanhamlett** [comment]
Just released a new version 3.0.10 where you can disable the status message in your `WakaTime.sublime-settings` file. I've also shortened the message.
