### ISSUE TITLE
Project detection

### ISSUE THREAD

**Issue by sisou** [wakatime/sublime-wakatime#36]
How can I tell WakaTime which files belong to the open project and which don't?

What I mean is: I don't have any parameters or special `.wakatime` files yet. My sublime has a project open, but I also occasionally edit files in sublime that do not belong to that project and are not in the project folder, but WakaTime is counting them towards this project as well (I think because of the `find_project_name_from_folders()` fallback detection). Now, is there a way that I can *only include* files that are in the project into the project on wakatime and all other files into **Unknown Project**?

**Comment by alanhamlett** [comment]
I could check if the current file is inside the project folder when detecting the project in `find_project_name_from_folders()`.

**Comment by alanhamlett** [comment]
Also, for now it might work to open a new ST window for files outside the project. That window shouldn't be associated with the project folder from the other window.

**Comment by alanhamlett** [comment]
Fixed in the latest version.
