### ISSUE TITLE
Move the api url to the settings file

### ISSUE THREAD

**Issue by Nodraak** [wakatime/sublime-wakatime#37]
Hello

I definitely *love* wakatime. But sadly, as a student, the pricing are quite expensive, so I am working on a custom dashboard. The problem is that on every update the hard coded api url is overwritten.

I am working on creating an `api_url` entry in the settings file but the settings loading is not that obvious and they are many configuration files.

**Comment by alanhamlett** [comment]
In v4.0.18 of sublime-wakatime you can add this to your `$HOME/.wakatime.cfg` file to customize the api url:
    api_url = https://wakatime.com/api/v1/heartbeats
