### ISSUE TITLE
Ignored api_key in .wakatime.cfg

### ISSUE THREAD

**Issue by albertosantini** [wakatime/sublime-wakatime#43]
After reading FAQ (see #42) and adding the api key in `.wakatime.cfg`, when SublimeText is started, it prompts to enter the wakatime.com  api key, the input field is filled with the api key.

Is this behavior expected? 
Is it mandatory to create the settings `WakaTime.sublime-settings`?

**Comment by alanhamlett** [comment]
Yes, that's the convention for Sublime Text so users are used to looking for a [Plugin].sublime-settings file for any plugin's configs. The ~/.wakatime.cfg is just for the common [wakatime cli](https://github.com/wakatime/wakatime).

Are you wanting your WakaTime.sublime-settings file on GitHub for backing up or sharing? If just for sharing, why not do this:

* remove your api key from `WakaTime.sublime-settings`
* commit `WakaTime.sublime-settings` to git and push to GitHub
* run `git update-index --assume-unchanged WakaTime.sublime-settings`
* add your api key back to `WakaTime.sublime-settings`

git should ignore changes in your `WakaTime.sublime-settings` from now on.

**Comment by albertosantini** [comment]
Nice suggestion. Thanks.

Minor suggestion.
I would change the text of the FAQ (in bold the changes) because "or" is a bit confusing:

_Make sure to update your api key in `$HOME/.wakatime.cfg` **(for wakatime cli)** or `WakaTime.sublime-settings` **(for plugin)** with your newly generated api key._

**Comment by alanhamlett** [comment]
Ok thanks!
