### ISSUE TITLE
I run sublime text show error... "sublime unable to find python binary wakatime needs to pythom worк"

### ISSUE THREAD

**Issue by jetfire21** [wakatime/sublime-wakatime#45]
I installed python and the wakatime plugin,but when I run sublime text show error... "sublime unable to find python binary wakatime needs to pythom worк"

**Comment by alanhamlett** [comment]
Install Python from https://www.python.org/downloads/ then restart Sublime Text and it should work :+1:

**Comment by jetfire21** [comment]
I reinstalled Python on drive c:\ and it worked! Thanks!

**Comment by alanhamlett** [comment]
Awesome! For future, if Python is not installed in the default location (C:\PythonXX) then you can include python.exe in your System PATH variable so WakaTime can find the python binary.
