### ISSUE TITLE
my time is not logged on os windows 8

### ISSUE THREAD

**Issue by jetfire21** [wakatime/sublime-wakatime#47]
I used before os windows 7 and wakatime there worked perfectly,but recently I started using os windows 8,there I install wakatime for sublime text and nonotepad++,but my time is not logged,I've tried everything:reinstalled several times,I wanted to see wakatime.log,but this file was not in the directory, rechecked python...all rdid not help :((

**Comment by alanhamlett** [comment]
First, glance over this: https://github.com/wakatime/wakatime#troubleshooting (the parts about turning on debug mode, and checking the `~/.wakatime.log`, Notepad++ log file, and Sublime Text console window for errors)

Then turn on debug mode in Sublime text from your User settings file, and in Notepad++ from your `~/.wakatime.cfg` file and look for error messages.

On windows, problems usually revolve around Python so can you type `python --version` from a cmd prompt?

**Comment by jetfire21** [comment]
~/.wakatime.cfg contain:
[settings]
debug = true
hidefilenames = true
api_key=f5b0171a-800a-44f8-8072-ad0768c774a4
offline = true

and file ~/.wakatime.log no exist in directory

python version 3.4.3

**Comment by jetfire21** [comment]
and wakatime api
{
  "data": {
    "created": "2015-06-23T20:50:42Z",
    "email": "freerun-2012@yandex.ru",
    "email_public": false,
    "full_name": null,
    "human_readable_website": null,
    "id": "08d9420e-889d-4a12-bd96-2b0fa1c1ba46",
    "last_heartbeat": null,
    "last_plugin": null,
    "last_plugin_name": null,
    "last_project": null,
    "location": null,
    "logged_time_public": false,
    "modified": "2015-06-23T21:02:55Z",
    "photo": "https://secure.gravatar.com/avatar/aa5bc8e54748406a41dd90cfc2c208e2?s=150&d=identicon",
    "photo_public": true,
    "plan": "basic",
    "timezone": "Asia/Baghdad",
    "username": null,
    "website": null
  }
}

**Comment by alanhamlett** [comment]
Do you have 2 WakaTime accounts? This account has never received a heartbeat, so you must have used a different account previously.

You should generate a new api key at https://wakatime.com/settings because you've shared it publicly here.

Do you have any errors in your `AppData\Roaming\Notepad++\plugins\config\WakaTime.log` file?

**Comment by jetfire21** [comment]
I registered a new account and for notepad++ now great time logged,but for sublime-text nothing logged...in file $home/.wakatime.log only data for notepad++...here last line:
{"now": "2015/06/24 14:29:40 RTZ 2 (\u00e7\u00e8\u00ec\u00e0)", "version": "4.0.16", "plugin": "notepadpp/393290 notepadpp-wakatime/2.0.0", "time": 1435145378.037707, "caller": "D:\\Program Files (x86)\\Notepad++\\plugins\\Config\\wakatime-master\\wakatime\\base.py", "lineno": 392, "file": "e:\\test.php", "level": "DEBUG", "message": {"response_code": 201}}
{"now": "2015/06/24 14:29:41 RTZ 2 (\u00e7\u00e8\u00ec\u00e0)", "version": "4.0.16", "plugin": "notepadpp/393290 notepadpp-wakatime/2.0.0", "time": 1435145379.435901, "caller": "D:\\Program Files (x86)\\Notepad++\\plugins\\Config\\wakatime-master\\wakatime\\base.py", "lineno": 392, "isWrite": true, "file": "e:\\test.php", "level": "DEBUG", "message": {"response_code": 201}}

**Comment by alanhamlett** [comment]
Only use one account. Delete your extra account and make sure your api key is using the correct account, because the plugins share the same config file so you can only log time to a single account.

Your Notepad++ plugin is working. Now check the Sublime Text console after deleting your extra account.

**Comment by jetfire21** [comment]
I now have only one account, I solved the problem..installed the new version of sublime text 3 and it worked! :) thanks for the replies

**Comment by alanhamlett** [comment]
Awesome, glad it's working!
