### ISSUE TITLE
Sublime wakatime doesn't work

### ISSUE THREAD

**Issue by thellimist** [wakatime/sublime-wakatime#50]
cat $HOME/.wakatime.log gives

`IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/EGG-INFO/top_level.txt'` 

I'm using sublime2 version 2.0.2 in OSX. Also cmd + shift + p -> wakatime opens my wakatime dashboard. But there is no data. Also sublime console is doesn't give any wakatime api logs(heartbeats).

**Comment by alanhamlett** [comment]
Can you turn on debug mode and look for errors in your Sublime Console and wakatime cli log file:

**Comment by thellimist** [comment]
There is no error in console
Console:
`[WakaTime] pythonw /Users/furkan/Library/Application Support/Sublime Text 2/Packages/WakaTime/packages/wakatime/cli.py --file /Users/furkan/Documents/Programming/go/own/src/github.com/thellimist/arcane-restapi/main.go --time 1436998100.772246 --plugin sublime/2221 sublime-wakatime/4.0.8 --key ********-****-****-****-********a3e6 --write --alternate-project arcane-restapi --cursorpos 265 --verbose`
wakatime.log:
`IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/EGG-INFO/top_level.txt'`

**Comment by alanhamlett** [comment]
Looks like it could be a problem with Python on your machine. If you have homebrew installed, the easiest fix is `brew install python`.

Can you reproduce this error by running this command in a terminal?
`python -c "import urllib, urllib2, httplib"`

If that gives you the permission denied error, then it's a problem with python and you should re-install it using homebrew or somehow fix the httplib module.

**Comment by thellimist** [comment]
@alanhamlett nothing happens when running `python -c "import urllib, urllib2, httplib"` command

**Comment by alanhamlett** [comment]
Ok, try this command and see if the error stops:

`sudo chmod a+r /Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/EGG-INFO/top_level.tx`

**Comment by alanhamlett** [comment]
It's working now?

**Comment by thellimist** [comment]
yes. thank you.
