### ISSUE TITLE
Not reporting LESS

### ISSUE THREAD

**Issue by montogeek** [wakatime/sublime-wakatime#51]
Hi guys!!

I worked all day with LESS files, after checking my Wakatime dashboard I noticed that is reported like "Other", I do not know if this only happens with ST or it's a general bug.
![screen shot 2015-07-24 at 18 01 08](https://cloud.githubusercontent.com/assets/1002461/8886349/490838fc-322e-11e5-9e71-79021e226c2e.png)
https://wakatime.com/@montogeek

**Comment by alanhamlett** [comment]
We use a combination of http://pygments.org in the plugins and our own server-side rules to detect languages. When pygments gets it wrong, we create a rule based on the file extension, which I just did. It's fixed now!

**Comment by montogeek** [comment]
Great! Thanks Alan
