### ISSUE TITLE
Internal python

### ISSUE THREAD

**Issue by albertosantini** [wakatime/sublime-wakatime#52]
Using the Sublime "internal" Python, does it make any sense instead of downloading and installing Python (version 3)?

(Maybe I am missing it, but I don't see any Python requirement in terms of version 2 or version 3 in the README or in the CLI).

**Comment by alanhamlett** [comment]
The embedded python that comes with ST2 and ST3 is missing some core libraries that WakaTime needs, like the `ssl` library needed to connect to the WakaTime api over https. Here is a Floobits blog post describing some of the issues: https://news.floobits.com/2015/08/17/sublime-text-plugin-api-its-python-sort-of/

**Comment by albertosantini** [comment]
I see.

Interesting link and I landed on the same final link suggested in that post:
https://packagecontrol.io/docs/dependencies

I have been using 2.7.10.
In the source code I read 3.4.3, if Python it is not installed.

You may add the minimumm requirements in the README about Python versions.

Thanks for the details.

**Comment by alanhamlett** [comment]
This should be solved now that we download and install python automatically on Windows. Also, with #54 we are detecting Python better using the Windows Registry.
