### ISSUE TITLE
Plugin freezes Sublime during downloading python

### ISSUE THREAD

**Issue by pravic** [wakatime/sublime-wakatime#53]
Subj.

Also, if python (both 2 & 3) installed without modifying PATH, WakaTime couldn't find it and trying to download & install on each Sublime start.

Sublime 3, Win7 x64, python 2.7.10 x86, python 3.5.0 x64.

**Comment by alanhamlett** [comment]
@pravic what folder are your python2 and python3 binaries located in? I've fixed the freezing in v4.0.17.

**Comment by pravic** [comment]
Thanks
