### ISSUE TITLE
Find python installation path

### ISSUE THREAD

**Issue by pravic** [wakatime/sublime-wakatime#54]
From #53:

If python (both 2 & 3) installed without modifying PATH, WakaTime couldn't find it and trying to download & install on each Sublime start.

It seems, you need to look on [InstallPath](http://stackoverflow.com/a/648552/736762) of suitable version.

Sublime 3, Win7 x64, python 2.7.10 x86, python 3.5.0 x64.

**Comment by pravic** [comment]
> @pravic what folder are your python2 and python3 binaries located in?

Custom. Like `f:/share/python/3/`, $PATH isn't modified, scripts runned directly (via shell) or through `py.exe`.

**Comment by alanhamlett** [comment]
v4.0.20 is now checking for Python in the windows registry, but uses python from your PATH first if it exists.
