### ISSUE TITLE
Is Dashboard only for Paid user??

### ISSUE THREAD

**Issue by SharkIng** [wakatime/sublime-wakatime#58]
I used WakaTime for couple weeks. I keep getting email said I worked xx mins for whatever project. (I am using Sublime a lot). Which seem that did log my work.

However, when I try to see the graph on website dashboard. nothing seen logged.

Nomatter what time perior. I am getting 0 sec on dashboard.

What happen??

**Comment by SharkIng** [comment]
When i try debug, I am getting 201 code. Which mean this is correct. But still cant see anything happen on Dashboard.....?

**Comment by gandarez** [comment]
@SharkIng it seems you didn't input your api key correctly. Check it out and come back here.

**Comment by alanhamlett** [comment]
@SharkIng can you email us and I'll help you get it fixed? support@wakatime.com
