### ISSUE TITLE
Incompatible dependency error on OSX

### ISSUE THREAD

**Issue by adisos** [wakatime/sublime-wakatime#64]
What is that?

I used it before on ubuntu, but moved to osx. Since that every time I launch sublime it shows this popup.

![image](https://cloud.githubusercontent.com/assets/592907/13981322/b02c417e-f10d-11e5-904e-6cc6ee2b5187.png)

**Comment by alanhamlett** [comment]
https://packagecontrol.io/docs/syncing

Basically you should uninstall, then reinstall the WakaTime package on OSX to fix it.
