### ISSUE TITLE
Dashboard empty

### ISSUE THREAD

**Issue by maiconpinto** [wakatime/sublime-wakatime#66]
Hello, my dashboard is empty. 

I saw that in error log, there are this:

{"now": "2016/06/15 13:26:53 +0000", "version": "6.0.5", "plugin": "sublime/3114 sublime-wakatime/7.0.6", "time": 1466008009.665068, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/home/maicon.pinto/.config/sublime-text-3/Packages/WakaTime/packages/wakatime/stats.py\", line 237, in get_file_head\n    text = fh.read(512000)\n  File \"/usr/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/usr/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 1377: invalid continuation byte\n"}

I run `apt-get update`, but it's not work. What Do I do? 

- SublimeText 3 (3114).

**Comment by alanhamlett** [comment]
Looks like it's working now?

**Comment by maiconpinto** [comment]
Hi @alanhamlett 

It's not work, yet. I reinstalled the wakatime, and nothing.

**Comment by alanhamlett** [comment]
Is this with your account under maiconsilva.pinto@gmail.com? That account has coding activity from Sublime Text 31 minutes ago.

Is the problem with a second computer or a different account?

**Comment by maiconpinto** [comment]
Ok. No problem. Thank you.

**Comment by alanhamlett** [comment]
It's fixed!
