### ISSUE TITLE
wakatime-core output: <_ssl._SSLSocket object at 0x03946200>

### ISSUE THREAD

**Issue by tosone** [wakatime/sublime-wakatime#67]
ERROR in my sublimeText.
[WakaTime] [ERROR] wakatime-core output: <_ssl._SSLSocket object at 0x03946200>

I do not think something wrong with my network.

But in my VSCode and atom are running well.

Env: 
windows: 10
SublimeText: 3114

**Comment by alanhamlett** [comment]
Is this fixed in the latest version of the plugin?
