### ISSUE TITLE
Mac Windows Folder Slash

### ISSUE THREAD

**Issue by derBoehm** [wakatime/sublime-wakatime#69]
Hey,

i'm working on both macOS and Windows but the project path has different slashes on wakatime:

\Projects\Web\ ... \ ... \file.php

/Projects/Web/ ... / ... /file.php

is it possible to change the slash before upload via the config?

Can't use the path for custom rules or i have to add two rules or only the last folder.

**Comment by alanhamlett** [comment]
Fixed by forcing forward slash from now on.
