### ISSUE TITLE
Is it possible to change it to the same project if the git address is the same? 

### ISSUE THREAD

**Issue by jaychsu** [wakatime/sublime-wakatime#72]
I don't know if this is a bug:

When I make a change in `OthProj`(it's a git submodule) in `RootProject`, my time will be counted under `RootProject`.

The structure is:

```
RootProject
|  OthProj (as submodule)
```

Is it possible to change it to the same project if the git address is the same? 

For this example, whether I'm in the `OthProj` in `RootProject`, or directly in `OthProj`, the time spent will be counted in `OthProj`.

**Comment by alanhamlett** [comment]
Yes, create a `.wakatime-project` file with the first line of that file `OthProj` then put that file in your `RootProject` folder. Any files edited inside that folder will now be assigned to `OthProj`.

**Comment by jaychsu** [comment]
It's work. Thx. :)

**Comment by jaychsu** [comment]
One more question, does it make sense to load proj info from `.gitsubmodule` if it exists?

**Comment by alanhamlett** [comment]
> does it make sense to load proj info from .gitsubmodule if it exists?

My understanding of [submodules](https://git-scm.com/docs/git-submodule) is they are for dependencies, not usually for development inside the submodules?

However, we can add support for submodules to [wakatime-cli](https://github.com/wakatime/wakatime) that can be enabled with a config setting in `~/.wakatime.cfg`.

**Comment by jaychsu** [comment]
OK, I'll submit a PR to do that :)

**Comment by alanhamlett** [comment]
wakatime/wakatime#105 added project detection from git submodules.
