### ISSUE TITLE
wakatime-core exited with status: 104

### ISSUE THREAD

**Issue by touno-project** [wakatime/sublime-wakatime#74]
How to fixed?

![image](https://user-images.githubusercontent.com/10203425/29863886-3688c0be-8d9b-11e7-8803-08ee9887c718.png)

**Comment by alanhamlett** [comment]
Make sure your api key is correct and matching https://wakatime.com/settings

![apikey](https://user-images.githubusercontent.com/522344/29880776-82922c18-8d5d-11e7-876e-fc41d212f527.png)


https://github.com/wakatime/sublime-wakatime#troubleshooting
