### ISSUE TITLE
wakatime-core output error [ESC][?1034h

### ISSUE THREAD

**Issue by brianbruggeman** [wakatime/sublime-wakatime#75]
Seems like there's a bug, but I think wakatime is also getting my updates.  So I'm not sure _why_ I have this problem... basic problem is a bunch of extraneous / non-valuable errors (pages and pages of errors):

```
[WakaTime] [ERROR] wakatime-core output: [?1034h
[WakaTime] [ERROR] wakatime-core output: [?1034h
[WakaTime] [ERROR] wakatime-core output: [?1034h
[WakaTime] [ERROR] wakatime-core output: [?1034h
[WakaTime] [ERROR] wakatime-core output: [?1034h
[WakaTime] [ERROR] wakatime-core output: [?1034h
[WakaTime] [ERROR] wakatime-core output: [?1034h
```

**Comment by alanhamlett** [comment]
What version of Python is installed on your machine, and if it's older than 3.6 are you able to update it?

**Comment by brianbruggeman** [comment]
I have python 2.7 and python 3.6 on my system.  

But as I understand it, this is a sublime text plugin which runs explicitly on python 3.3 and [_there's no way to update it_](https://forum.sublimetext.com/t/upgrade-embedded-python-to-3-6/28883/9).  While I disagree with the author's stance for a variety of reasons, I don't think there's any push to move the developers to upgrade and break some of their ecosystem.

**Comment by alanhamlett** [comment]
Can you try the latest version 8.1.0 of the WakaTime plugin? It prefers Python3 now, so might have fixed this issue.

**Comment by alanhamlett** [comment]
Fixed now that we're using Go instead of Python for wakatime-cli.
