### ISSUE TITLE
ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by OpenWaygate** [wakatime/sublime-wakatime#77]
[WakaTime] [DEBUG] C:\Users\11097\AppData\Roaming\WakaTime\python\pythonw C:\Users\11097\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\cli.py --entity C:\Users\11097\.wakatime.cfg --time 1508239683.975857 --plugin sublime/3143 sublime-wakatime/7.0.23 --key XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXb41a --cursorpos 80 --exclude ^/tmp/ --exclude ^/etc/ --exclude ^/var/(?!www/).* --exclude COMMIT_EDITMSG$ --exclude PULLREQ_EDITMSG$ --exclude MERGE_MSG$ --exclude TAG_EDITMSG$ --include .* --verbose

[WakaTime] [ERROR] wakatime-core exited with status: 3221226505

[WakaTime] [ERROR] wakatime-core output: Fatal Python error: Py_Initialize: unable to load the file system codec

ImportError: No module named 'encodings'

**Comment by alanhamlett** [comment]
This is a problem with Python. Can you try re-installing Python 3.6 from https://www.python.org/downloads/ as Administrator?
