### ISSUE TITLE
Sublime Text 3 Plugin not logging data on macOS

### ISSUE THREAD

**Issue by dblalock** [wakatime/sublime-wakatime#78]
I went through the install steps for sublime text 3, including entering my API key, but the dashboard claims it’s received no data. ~/.wakatime.log exists but is empty:

cat ~/.wakatime.log | wc -c
       0

The user agents endpoint API just displays (in the browser):

{
  "data": []
}

After turning on Debug mode, I obtained the following (relevant) lines in the console:

    reloading settings Packages/User/WakaTime.sublime-settings
    reloading settings Packages/User/WakaTime.sublime-settings
    [WakaTime] [DEBUG] pythonw /Users/<my username>/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/cli.py --entity /Users/<my username>/Library/Application Support/Sublime Text 3/Packages/User/WakaTime.sublime-settings --time 1508363680.217604 --plugin sublime/3143 sublime-wakatime/7.0.23 --key XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXa1b2 --cursorpos 53 --verbose --extra-heartbeats
    [WakaTime] [DEBUG] wakatime-core exited with status: 102

Relevant info from the .wakatime.log:

    {"now": "2017/10/18 20:03:32 -0400", "version": "8.0.3", "plugin": "sublime/3143 sublime-wakatime/7.0.23", "time": 1508371407.9320819, "caller": "/Users/<my username>/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/main.py", "lineno": 189, "file": "/Users/<my username>/.wakatime.log", "level": "WARNING", "message": "{'SSLError': u'[Errno 1] _ssl.c:490: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm', 'traceback': 'Traceback (most recent call last):\\n  File \"/Users/<my username>/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/main.py\", line 158, in send_heartbeat\\n    verify=not nosslverify)\\n  File \"/Users/<my username>/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/requests/sessions.py\", line 535, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/Users/<my username>/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/requests/sessions.py\", line 488, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/Users/<my username>/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/requests/sessions.py\", line 609, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/Users/<my username>/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/requests/adapters.py\", line 497, in send\\n    raise SSLError(e, request=request)\\nSSLError: [Errno 1] _ssl.c:490: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm\\n'}"}

This error apparently happens every ~4 minutes.

I’m on macOS 10.12.6, Sublime Text 3.0 build 3143.

**Comment by FrancescoMussi** [comment]
Same here.
Sublime 3 - MacOS.
Wakatime it is not updating and recording my current working time.

**Comment by FrancescoMussi** [comment]
In my case the error was pretty embarassing.
I just pasted the settings suggested [here](https://github.com/wakatime/wakatime#configuring)  without even check them...

And of course in the file `.wakatime.dfg`  this line was the guilty one:

`proxy = https://user:pass@localhost:8080`

After removing that line everything works fine.

Shame on me!

Great component. I love it!

**Comment by alanhamlett** [comment]
@dblalock which version of Python are you using? Anaconda Python and older versions of Python 2 use an ssl module that can't verify SSL certs correctly. Can you try upgrading Python to Python 3?

**Comment by dblalock** [comment]
$ python --version
    Python 2.7.13 :: Anaconda 1.9.2 (x86_64)

I'm not really willing to change my default python, but if there's a way to have the plugin use a virtualenv I'd be up for trying that.

**Comment by alanhamlett** [comment]
Fixed with 385ba818cccf4513936a907981b54bc81c02e847 and released in v7.0.25 today.

After Package Control upgrades your WakaTime plugin, change your `python_binary` setting to:
`"/usr/bin/python"`
