### ISSUE TITLE
SQL Not Recognized in Sublime with Wakatime

### ISSUE THREAD

**Issue by wushengzhong** [wakatime/sublime-wakatime#82]
![image](https://user-images.githubusercontent.com/8701128/36228753-f84c22d2-1189-11e8-98c7-b17eff367e3a.png)

I saved my sql script as *.SQL and it seem that Wakatime cannot track this properly. Is is because the sql extension is in upper-case letters? Sublime cannot recognize this if I saved in lower-case letters.

**Comment by alanhamlett** [comment]
This is fixed now. Thanks for helping improve language detection!
