### ISSUE TITLE
wakatime-core exited with status: 102

### ISSUE THREAD

**Issue by stevenyvette** [wakatime/sublime-wakatime#85]
I am using  **wakatime 8.1** with **sublime3**  & **windows10** .
It didn't work in the dashboard and I have check my api-key in **WakaTime.sublime-settings**, nothing wrong.
 
I found the following in sublime console:
```
[WakaTime] [DEBUG] pythonw C:\Users\inesa\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\cli.py --entity E:\horizon-dev\openstack_dashboard\urls.py --time 1523584123.118488 --plugin sublime/3143 sublime-wakatime/8.1.0 --key XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX23a2 --alternate-project horizon-dev --cursorpos 1356 --exclude ^/tmp/ --exclude ^/etc/ --exclude ^/var/(?!www/).* --exclude COMMIT_EDITMSG$ --exclude PULLREQ_EDITMSG$ --exclude MERGE_MSG$ --exclude TAG_EDITMSG$ --include .* --verbose
[WakaTime] [DEBUG] wakatime-core exited with status: 102
```

Plz help me ~ :) thx

**Comment by alanhamlett** [comment]
Exit code 102 means an API error. Can you check your `~/.wakatime.log` for the error message?

**Comment by stevenyvette** [comment]
@alanhamlett 
Thx.
It works now but I have done nothing.... 😅 Maybe just something wrong with the network,
Still thx for your quick reply~
