### ISSUE TITLE
Wakatime fails to initialize on Sublime Text 3.1.1

### ISSUE THREAD

**Issue by ethanmay** [wakatime/sublime-wakatime#87]
Sublime Text 3.1.1 came out yesterday and it appears that the Wakatime extension is failing to initialize. I removed the package, attempted to reinstall, and the status bar says "Wakatime Initializing" indefinitely. Furthermore, I am not presented with a text box to enter my API key.

**Comment by alanhamlett** [comment]
The text box asking for your API Key is only needed once, it saves your API Key to sublime's settings afterwards:
![68747470733a2f2f77616b6174696d652e636f6d2f7374617469632f696d672f53637265656e53686f74732f7375626c696d652d77616b6174696d652d73657474696e67732d6d656e752e706e673f763d33](https://user-images.githubusercontent.com/522344/40091134-d041a8c0-586a-11e8-8df0-1e23427150af.png)

After typing in a file, the status bar should change to `WakaTime OK`.
