### ISSUE TITLE
Wakatime is trying to use Python3 after I uninstalled it

### ISSUE THREAD

**Issue by jmona789** [wakatime/sublime-wakatime#88]
I installed python3 using brew earlier today but eventually decided to stick with python2.7  I noticed my wakatime plugin wasnt updating my daskboard so I set debug to true and checked out my sublime console and was getting `[WakaTime] [DEBUG] wakatime-core exited with status: 102` I figured it might have been because I insallted python 3 so I uninstalled it with brew and now the console is saying "[WakaTime] [ERROR] [Errno 2] No such file or directory: 'python3'" How do I fix tihs so wakatime using python 2.7 instad of trying to use 3

**Comment by jmona789** [comment]
UPDATE: restarted sublime but now I'm back to getting `[WakaTime] [DEBUG] wakatime-core exited with status: 102`

**Comment by alanhamlett** [comment]
Was the plugin reporting `No such file or directory: 'python3'` happening after restarting Sublime Text and uninstalling Python3? Python is detected once when ST starts, so it could just be using Python3 when it wasn't available after uninstalling.

The second error was probably from downtime we experienced earlier today. Does the status bar in ST show `WakaTime OK` now?

**Comment by jmona789** [comment]
Yes, it shows `WakaTime OK` now and it seems to be working.  Thanks for the help
