### ISSUE TITLE
Python interpreter can't find __main__ module

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/sublime-wakatime#9]
~/.wakatime.log has this error:
/usr/bin/python: can't find '**main**' module in '/home/user/.config/sublime-text-3/Installed Packages/WakaTime.sublime-package/packages/wakatime/wakatime.py'

This has been reported on OS X and Ubuntu.

**Comment by guru81** [comment]
hi see  python /root/Desktop/1 2.py
/usr/bin/python: can't find '__main__' module in '/root/Desktop/1'
don't use space
 python /root/Desktop/1/2.py
sh: 1: ./l2: not found
work

**Comment by alanhamlett** [comment]
Huh? O_o
