### ISSUE TITLE
Waste too much time when starting debugging

### ISSUE THREAD

**Issue by mxi-box** [wakatime/sublime-wakatime#90]
work on windows7, sublime text 3.1.1, wakatime plugin 8.1.1.

```
{"now": "2018/09/11 15:36:46 +0800", "version": "10.2.1", "plugin": "sublime/3176 sublime-wakatime/8.1.1", "time": 1536651371.076608, "caller": "C:\\Users\\Administrator\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\api.py", "lineno": 53, "file": "E:\\computerprogramme\\luogu\\p3057.cpp", "level": "DEBUG", "message": "Sending heartbeats to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk"}
{"now": "2018/09/11 15:36:46 +0800", "version": "10.2.1", "plugin": "sublime/3176 sublime-wakatime/8.1.1", "time": 1536651371.076608, "caller": "C:\\Users\\Administrator\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\api.py", "lineno": 59, "file": "E:\\computerprogramme\\luogu\\p3057.cpp", "level": "DEBUG", "message": "[{'dependencies': ['cstring', 'cassert', 'iostream', 'algorithm', 'cstdio'], 'cursorpos': '476', 'time': 1536651371.076608, 'category': None, 'lineno': None, 'language': 'C++', 'branch': None, 'type': 'file', 'is_write': False, 'project': None, 'lines': 43, 'user_agent': 'wakatime/10.2.1 (Windows-7-6.1.7601-SP1) Python3.5.2.final.0 sublime/3176 sublime-wakatime/8.1.1', 'entity': 'E:/computerprogramme/luogu/p3057.cpp'}]"}
{"now": "2018/09/11 15:37:13 +0800", "version": "10.2.1", "plugin": "sublime/3176 sublime-wakatime/8.1.1", "time": 1536651371.076608, "caller": "C:\\Users\\Administrator\\AppData\\Roaming\\Sublime Text 3\\Packages\\WakaTime\\packages\\wakatime\\api.py", "lineno": 165, "file": "E:\\computerprogramme\\luogu\\p3057.cpp", "level": "DEBUG", "message": "{'response_code': 202, 'results': [[{'data': {'id': '###'}}, 201]]}"}
```

i found that it cost too much time requesting this when i press ctrl+b to compile my program.

> https://api.wakatime.com/api/v1/users/current/heartbeats.bulk

maybe it was blocked by GFW. could you make it async?

**Comment by alanhamlett** [comment]
It's async already, using [threading](https://docs.python.org/3/library/threading.html):

https://github.com/wakatime/sublime-wakatime/blob/f61a34eda710cd928c8fe3983f25d245fcd96491/WakaTime.py#L461

**Comment by alanhamlett** [comment]
That's just a warning, it's normal and not an error. Turn off debug mode, then delete your `~/.wakatime.log` file.

Let's find the issue here. Is it one of these?

1. Sublime Text isn't tracking your coding activity, and your dashboard is empty.
2. Sublime Text is tracking, but it's lagging when typing.
3. Sublime Text is tracking your activity, but you get warnings in your log file sometimes.

Which of the 3 above is the issue you're experiencing?

**Comment by iamntz** [comment]
I also had this issue when using `build` on Sublime. In fact, this was the reason I ditched Waka a while back (meanwhile I forgot but now it comes back to me 🦀 )

_However_... I've extracted latest Python ([3.7 at this moment](https://www.python.org/downloads/release/python-370/)) as `Windows x86-64 embeddable zip file` into a folder, and manually specify that folder path in the config:

```
"python_binary": "C:\\Python37\\python.exe",
```

I don't want to jinx it, but it _seems_ to be alright.

**Comment by alanhamlett** [comment]
@mxi-box after turning off debug mode, does the lagging get better? Or is it slow regardless of the debug setting?

@iamntz with Python 3.7 just want to check that it's still working ok?

**Comment by iamntz** [comment]
Update: in the last week i've noticed only a couple of time the editor has froze, so _I guess_ the python version has something to do with it.

**Comment by alanhamlett** [comment]
Most likely fixed now that we're using Go instead of Python for wakatime-cli.
