### ISSUE TITLE
Seems unhappy with network drives

### ISSUE THREAD

**Issue by vincemulhollon** [wakatime/sublime-wakatime#93]
Generally everything is working, including other projects.

However, with a project accessed via a network drive, the plugin seems unhappy.  Environment is Windows 10, Active Directory, nothing terribly exciting.  Debug logs while working on a network drive project look like:

```
{"now": "2019/03/28 15:59:13 -0500", "version": "10.6.1", "plugin": "sublime/3200 sublime-wakatime/8.3.3", "file": "\\\\tftp\\tftpboot\\boot.ipxe", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
```

I assure you that file most certainly does exist.

If I network map `\\tftp\tftpboot` to a drive letter, perhaps `T:` as in TFTP, then open the project at the location `T:\tftpboot.sublime-project` (instead of `\\tftp\tftpboot\tftpboot.sublime-project`), then the plugin works great and properly logs everything and all is well.

**Comment by alanhamlett** [comment]
Similar issues from the past:
wakatime/vscode-wakatime#67
wakatime/wakatime#72

First, let me release an update to the WakaTime Sublime plugin with the lastest [wakatime-cli](https://github.com/wakatime/wakatime).

**Comment by alanhamlett** [comment]
Now that we're using Go instead of Python, does this issue still exist?

**Comment by alanhamlett** [comment]
Related to https://github.com/wakatime/vscode-wakatime/issues/244.

**Comment by gandarez** [comment]
Remote file detection has been implemented in the new wakatime-cli.
