### ISSUE TITLE
WakaTime hides other messages in sublime

### ISSUE THREAD

**Issue by KES777** [wakatime/sublime-wakatime#97]
![_](https://user-images.githubusercontent.com/799021/57604165-2dfd3f00-756c-11e9-950d-50c633ecd955.jpg)

When I am searching something there are messages from search panel on status bar.

But those messages are hidden by waka

**Comment by alanhamlett** [comment]
Is this a bug in Sublime Text?

We use the official Sublime Text API to set the wakatime status bar text:
https://github.com/wakatime/sublime-wakatime/blob/cde8f8f1de1e0b527ae53a18680801f0846b83d7/WakaTime.py#L213

**Comment by JosephusPaye** [comment]
Just came to report the same issue 😄.

While we wait for a potential fix in Sublime, would it be possible perhaps to have an option that disables the status messages?

**Comment by OpenWaygate** [comment]
I came across this problem and created an issue [here](https://forum.sublimetext.com/t/x-of-y-matches-disappear-in-status-bar/46417/3). I have to disable it every time I want search something.

**Comment by arnemahl** [comment]
What about an option for this plugin to turn of the WakaTime status? I would prefer being able to use all the features of Sublime Text over getting the WakaTime status in Sublime. (After all it's really easy to open the WakaTime dashboard from Sublime whenever I want that info :pray:)

**Comment by OpenWaygate** [comment]
I have comment these lines in `\Packages\WakaTime\WakaTime.py` (the line number may different)

https://github.com/wakatime/sublime-wakatime/blob/cde8f8f1de1e0b527ae53a18680801f0846b83d7/WakaTime.py#L209-L213

The message in status line from wakatime disappears but dashboard still update your coding activity.
