### ISSUE TITLE
Disable api key prompt if already set in main config

### ISSUE THREAD

**Issue by soifou** [wakatime/sublime-wakatime#98]
I'm using only the main config file (`.wakatime.cfg`) to set my api_key and some other settings I need for. I don't need to set any overriden value in Wakatime.sublime-settings.

However each time I open a new Sublime Text instance, Wakatime prompt me to enter my api key even if it does not prevent it from working as it should. So each time, I hit escape key to skip the prompt but this is kind of annoying.

Could you implement an option to not prompt for an api_key or review the logic behind this ? If this is not intended, I could give you some additionnal informations about my setup.

**Comment by alanhamlett** [comment]
Implemented in v8.6.0 just released.

**Comment by soifou** [comment]
@alanhamlett 

Thanks for the fix but it does still prompt with v8.6.0 :/
My WAKATIME_HOME is set to ~/.config/wakatime
My wakatime config ~/.config/wakatime/.wakatime.cfg
No user defined Wakatimesublime-settings

**Comment by alanhamlett** [comment]
Sorry, probably because of a bug when parsing the config file. Should be fixed now in 8.6.1, can u see if it stops prompting after updating?

**Comment by soifou** [comment]
The behaviour has changed.

Now, first time it continues prompting and **creates a sublime-settings file with my api_key**. The next time it stops prompting. 

I don't want or need to manage several config files for my api key.

**Comment by alanhamlett** [comment]
After upgrading to v8.7.0 you can delete your user sublime-settings file and restart Sublime for it to use the common config file without re-creating the sublime-settings file.

**Comment by soifou** [comment]
Yes this is now perfect, thanks a lot @alanhamlett  !
